global:
  scrape_interval: 5s  # how often to scrape targets

scrape_configs:
  - job_name: 'mern-backend'
    static_configs:
      - targets: ['host.docker.internal:5000']  # if using Docker
        # or ['localhost:3000'] if running natively
